language: erlang
matrix:
  include:
    - os: linux
      dist: xenial
      otp_release: 19.3
    - os: linux
      dist: xenial
      otp_release: 20.3.8.5
    - os: linux
      dist: xenial
      otp_release: 21.1
    - os: osx
      language: generic
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  ## should eventually use a tap that has previous erlang versions here
  ## as this only uses the latest erlang available via brew
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install erlang rebar3; fi
script:
  - rebar3 compile
addons:
  apt:
    packages:
      - g++
      - make
      - cmake
      - libuv1-dev
      - libssl-dev
